### ISSUE TITLE
[OEP-55] 20/04 - 04/05

### ISSUE THREAD

**Issue by mariajgrimaldi** [openedx/openedx-events#204]
## Description
Ticket to keep track of the work done around the maintainers pilot.

## Tasks
- [x] Add dependabot, example PR: https://github.com/openedx/docs.openedx.org/blob/main/.github/dependabot.yml
- [x] Add CODEOWNERs as POC
- [x] Review PR https://github.com/openedx/openedx-events/pull/202

**Comment by mariajgrimaldi** [comment]
Hi @felipemontoya, please feel free to assign yourself any of the pending tasks. Thanks!
