### ISSUE TITLE
Address documentation improvement suggestions from community feedback

### ISSUE THREAD

**Issue by mariajgrimaldi** [openedx/openedx-events#358]
## Description
Feedback from a recent developer experience survey has highlighted several areas where the current documentation can be improved to better support developers using the Open edX platform. This issue addresses these concerns by enhancing the documentation to make it more comprehensive, accessible, and user-friendly.

The overall objective of this issue is to address all community feedback to improve the library documentation.

```[tasklist]
### Tasks
- [ ] https://github.com/openedx/openedx-events/issues/360
- [ ] https://github.com/openedx/openedx-events/issues/361
- [ ] https://github.com/openedx/openedx-events/issues/362
- [ ] https://github.com/openedx/openedx-events/issues/363
- [ ] https://github.com/openedx/openedx-events/issues/364
- [ ] https://github.com/openedx/openedx-events/issues/365
- [ ] https://github.com/openedx/openedx-events/issues/366
- [ ] https://github.com/openedx/openedx-events/issues/367
- [ ] https://github.com/openedx/openedx-events/issues/368
- [ ] https://github.com/openedx/openedx-events/issues/369
- [ ] https://github.com/openedx/openedx-events/issues/370
- [ ] https://github.com/openedx/openedx-events/issues/357
- [ ] https://github.com/openedx/openedx-events/issues/421
```

**Comment by mariajgrimaldi** [comment]
Some suggestions I've gathered from the community survey on the challenges section:

> I would only improve the documentation a little bit. For example, in the section on creating a filter it talks about two different filters, which may cause confusion. I think it would be good to show an example of a filter implemented from start to finish, which contains all or at least most of the functionality offered by the library. additionally, the openedx-filters-samples repository has a great variety of examples, but it shows the filter creation part, but not (I think) the filter usage which is also important.

> At the beginning it was understanding how the filters and events worked, also the difference that exists between each one. But in general it has good documentation to learn how to use it and create new ones.
> There is a link to see live examples, https://github.com/openedx/openedx-filters/blob/main/docs/quickstarts/use-filters-to-change-enrollment.rst. This is good, but that repository is a bit out of date in references.

> The first and only challenge I had was understanding how it works (that you need a point in edx-platform and create a pipeline), but then it was very useful.
